sudo: required
services:
  - docker

before_install:
  - docker build -t docker-mult-container -f ./clinet/Dockerfile.dev .

script:
  - docker run -e CI=true docker-mult-container npm test

after_success:
  - docker build -t docker-multi-client ./client
  - docker build -t docker-multi-nginx ./nginx
  - docker build -t docker-multi-server ./server
  - docker build -t docker-multi-worker ./worker

# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push docker-multi-client
  - docker push docker-multi-nginx
  - docker push docker-multi-server
  - docker push docker-multi-worker 
